<?php
include("includes/lib_admin.inc");
include("includes/colors.inc");

$MARGIN = 20;
?>
<html>
<head>
  <title><?php echo $Site->name; ?></title>
  <style type="text/css">
<?php include("style.css"); ?>
  </style>
</head>
<body bgcolor="<?php echo $bgcolor; ?>" topmargin="0" leftmargin="0">
<br><br>
<div align="center">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
  <tr>
    <td width="<?php echo $MARGIN; ?>"><img src="<?php echo $PATH; ?>/images/spacer.gif" width="<?php echo $MARGIN; ?>" height="1"></td>
    <td class="general" width="99%">
<!-- Begin content -->
