<?php $selected = $rating == "1" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="1">1</option>
<?php $selected = $rating == "2" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="2">2</option>
<?php $selected = $rating == "3" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="3">3</option>
<?php $selected = $rating == "4" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="4">4</option>
<?php $selected = $rating == "5" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="5">5</option>
<?php $selected = $rating == "6" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="6">6</option>
<?php $selected = $rating == "7" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="7">7</option>
<?php $selected = $rating == "8" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="8">8</option>
<?php $selected = $rating == "9" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="9">9</option>
<?php $selected = $rating == "10" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="10">10</option>
