<?php $selected = $state == "AL" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="AL">Alabama</option>
<?php $selected = $state == "AK" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="AK">Alaska</option>
<?php $selected = $state == "AZ" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="AZ">Arizona</option>
<?php $selected = $state == "AR" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="AR">Arkansas</option>
<?php $selected = $state == "CA" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="CA">California</option>
<?php $selected = $state == "CO" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="CO">Colorado</option>
<?php $selected = $state == "CT" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="CT">Connecticut</option>
<?php $selected = $state == "DE" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="DE">Delaware</option>
<?php $selected = $state == "DC" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="DC">Dist. of Columbia</option>
<?php $selected = $state == "FL" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="FL">Florida</option>
<?php $selected = $state == "GA" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="GA">Georgia</option>
<?php $selected = $state == "HI" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="HI">Hawaii</option>
<?php $selected = $state == "ID" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="ID">Idaho</option>
<?php $selected = $state == "IL" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="IL">Illinois</option>
<?php $selected = $state == "IN" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="IN">Indiana</option>
<?php $selected = $state == "IA" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="IA">Iowa</option>
<?php $selected = $state == "KS" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="KS">Kansas</option>
<?php $selected = $state == "KY" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="KY">Kentucky</option>
<?php $selected = $state == "LA" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="LA">Louisiana</option>
<?php $selected = $state == "ME" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="ME">Maine</option>
<?php $selected = $state == "MD" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="MD">Maryland</option>
<?php $selected = $state == "MA" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="MA">Massachusetts</option>
<?php $selected = $state == "MI" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="MI">Michigan</option>
<?php $selected = $state == "MN" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="MN">Minnesota</option>
<?php $selected = $state == "MS" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="MS">Mississippi</option>
<?php $selected = $state == "MO" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="MO">Missouri</option>
<?php $selected = $state == "MT" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="MT">Montana</option>
<?php $selected = $state == "NE" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="NE">Nebraska</option>
<?php $selected = $state == "NV" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="NV">Nevada</option>
<?php $selected = $state == "NH" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="NH">New Hampshire</option>
<?php $selected = $state == "NJ" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="NJ">New Jersey</option>
<?php $selected = $state == "NM" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="NM">New Mexico</option>
<?php $selected = $state == "NY" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="NY">New York</option>
<?php $selected = $state == "NC" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="NC">North Carolina</option>
<?php $selected = $state == "ND" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="ND">North Dakota</option>
<?php $selected = $state == "OH" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="OH">Ohio</option>
<?php $selected = $state == "OK" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="OK">Oklahoma</option>
<?php $selected = $state == "OR" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="OR">Oregon</option>
<?php $selected = $state == "PA" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="PA">Pennsylvania</option>
<?php $selected = $state == "RI" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="RI">Rhode Island</option>
<?php $selected = $state == "SC" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="SC">South Carolina</option>
<?php $selected = $state == "SD" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="SD">South Dakota</option>
<?php $selected = $state == "TN" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="TN">Tennessee</option>
<?php $selected = $state == "TX" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="TX">Texas</option>
<?php $selected = $state == "UT" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="UT">Utah</option>
<?php $selected = $state == "VT" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="VT">Vermont</option>
<?php $selected = $state == "VA" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="VA">Virginia</option>
<?php $selected = $state == "WA" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="WA">Washington</option>
<?php $selected = $state == "WV" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="WV">West Virginia</option>
<?php $selected = $state == "WI" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="WI">Wisconsin</option>
<?php $selected = $state == "WY" ? "selected" : ""; ?>
<option <?php echo $selected; ?> value="WY">Wyoming</option>
